version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/home/app
    ports:
      - "8081:8081"
      - "8501:8501"
    entrypoint: ["make", "run"]
    networks:
      - susbot-network

networks:
  susbot-network:
    driver: bridge 